// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StateMachine
{
    using System.Xml;
    using System.Xml.Linq;
    using System.Collections;
    using System.Collections.Generic;
    using System;
    
    
    #line 1 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class StateMachine : StateMachineBase
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write("\r\n");
            
            #line 9 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"

	string initialState = "";
	HashSet<string> states = new HashSet<string>();
    HashSet<string> events = new HashSet<string>();
	IList<string> transitions = new List<string>();
	

	XDocument xmlFile = XDocument.Load(xml_file);

    // we assume that the first attribute of Root node is the
    // namespace declaration
    XNamespace ns = xmlFile.Root.FirstAttribute.Value;
    XElement x_scxml = xmlFile.Element(ns + "scxml");
    initialState = x_scxml.Attribute("initial").Value;
    var x_states = x_scxml.Elements(ns + "state");

    foreach (XElement x_state in x_states)
    {
        string startState = x_state.Attribute("id").Value;
        states.Add(startState);
        //XElement x_transition = x_state.Element(ns + "transition");
		var x_transitions = x_state.Elements(ns + "transition");
		foreach (XElement x_transition in x_transitions)
		{
			string trigger = x_transition.Attribute("event").Value;
			events.Add(trigger);
			string targetState = x_transition.Attribute("target").Value;
			string transition = "";
			if (x_transition.Attribute("action") != null)
            {
				transition = startState + "|" + trigger + "|" + targetState + "|" + x_transition.Attribute("action").Value;  
			}
			else
            {
				transition = startState + "|" + trigger + "|" + targetState;  
            }
			transitions.Add(transition);

        }
    }

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections;\r\n\r\nnamespace StateMachine\r\n{\r\n\tpublic en" +
                    "um State \r\n\t{\r\n\t\t");
            
            #line 57 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"

			string ssep = "";
			foreach(string s in states)
			{
				WriteLine(ssep + s);
				ssep = ",";
			}
		
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\tpublic enum Event \r\n\t{\r\n\t\t");
            
            #line 69 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"

			string esep = "";
			foreach(string e in events)
			{
				WriteLine(esep + e);
				esep = ",";
			}
		
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n    public abstract class AbstractStateMachine\r\n    {\r\n        private Stat" +
                    "e _currentState;\r\n        private IList transitions = new ArrayList();\r\n\r\n      " +
                    "  public delegate void Action();\r\n\r\n\t\t");
            
            #line 86 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"

			foreach(string t in transitions)
			{
				string[] t_array = t.Split('|');
				if (t_array.Length == 4) // scxml contains action
					WriteLine("public abstract void " + t_array[3] + "Action();");
				//else
				//	WriteLine("public abstract void " + t_array[0] + "To" + t_array[2] + "Action();"); 
			}
		
            
            #line default
            #line hidden
            this.Write("\r\n        public AbstractStateMachine()\r\n        {\r\n\t\t\t_currentState = State.");
            
            #line 99 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(initialState));
            
            #line default
            #line hidden
            this.Write(@";
			SetupTransitions();
		}

        public State CurrentState
        {
            get { return _currentState; }
			set { _currentState = value; }
        }

		public void FireEvent(Event e)
        { 
            foreach (Transition trans in transitions)
            {
                if (CurrentState == trans.StartState && e == trans.Trigger)
                {
                    CurrentState = trans.EndState;
					if (trans.Fire != null)
						trans.Fire();
					break;
                }
            }
        }

		private void SetupTransitions()
		{
            ");
            
            #line 125 "C:\Projects\Fun\StateMachine\StateMachineGenerator\StateMachine\StateMachine.tt"

				foreach(string t in transitions)
				{
					string[] t_array = t.Split('|');
					
					if (t_array.Length == 4) // scxml contains action
                    {
						Write("AddTransition(");
						Write("ConvertStringToState(\"" + t_array[0] + "\"), ");
						Write("ConvertStringToEvent(\"" + t_array[1] + "\"), ");
						Write("ConvertStringToState(\"" + t_array[2] + "\"), ");
						WriteLine("new Action(" + t_array[3] + "Action));");
                    }
					else
                    {
						Write("AddTransition(");
						Write("ConvertStringToState(\"" + t_array[0] + "\"), ");
						Write("ConvertStringToEvent(\"" + t_array[1] + "\"), ");
						WriteLine("ConvertStringToState(\"" + t_array[2] + "\"));");
                    }
				}
			
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tprivate void AddTransition(State start, Event e, State end)\r\n        {\r\n" +
                    "            transitions.Add(new Transition(start, e, end));\r\n        }\r\n\r\n\t\tpriv" +
                    "ate void AddTransition(State start, Event e, State end, Action a)\r\n        {\r\n  " +
                    "          transitions.Add(new Transition(start, e, end, a));\r\n        }\r\n\r\n\t\tpri" +
                    "vate State ConvertStringToState(string token)\r\n        {\r\n            return (St" +
                    "ate)Enum.Parse(typeof(State), token);\r\n        }\r\n\r\n        private Event Conver" +
                    "tStringToEvent(string token)\r\n        {\r\n            return (Event)Enum.Parse(ty" +
                    "peof(Event), token);\r\n        }\r\n    }\r\n\r\n\tinternal class Transition\r\n    {\r\n   " +
                    "     private State _startState;\r\n        private Event _trigger;\r\n        privat" +
                    "e State _endState;\r\n\t\tprivate AbstractStateMachine.Action _action;\r\n\r\n\t\tpublic T" +
                    "ransition()\r\n        {\r\n\t\t}\r\n\r\n\t\tpublic Transition(State start, Event e, State e" +
                    "nd)\r\n        {\r\n            _startState = start;\r\n            _trigger = e;\r\n   " +
                    "         _endState = end;\r\n        }\r\n\r\n        public Transition(State start, E" +
                    "vent e, State end, AbstractStateMachine.Action a)\r\n        {\r\n            _start" +
                    "State = start;\r\n            _trigger = e;\r\n            _endState = end;\r\n       " +
                    "     _action = a;\r\n        }\r\n\r\n\t\tpublic State StartState\r\n        {\r\n          " +
                    "  get { return _startState; }\r\n        }\r\n\r\n\t\tpublic Event Trigger\r\n        {\r\n " +
                    "           get { return _trigger; }\r\n        }\r\n\r\n        public State EndState\r" +
                    "\n        {\r\n            get { return _endState; }\r\n        }\r\n\r\n\t\tpublic Abstrac" +
                    "tStateMachine.Action Fire\r\n\t\t{\r\n\t\t\tget { return _action; }\r\n\t\t}\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class StateMachineBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
    }
    #endregion
}
